<?php
/*
 * @package		Joomla.Framework
 * @copyright	Copyright (C) Open Source Matters, Inc. All rights reserved.
 * @license		GNU General Public License version 2 or later; see LICENSE.txt
 * @component Phoca Component
 * @copyright Copyright (C) Jan Pavelka www.phoca.cz
 * @license http://www.gnu.org/copyleft/gpl.html GNU General Public License version 2 or later;
 */
namespace Joomla\Component\PhocaCart\Api\Controller;

use Joomla\CMS\Extension\LegacyComponent;
use Joomla\CMS\Form\Form;
use Joomla\CMS\MVC\Controller\ApiController;
use Joomla\CMS\MVC\Model\BaseDatabaseModel;
use Joomla\CMS\MVC\Model\LegacyModelLoaderTrait;

// phpcs:disable PSR1.Files.SideEffects
\defined('_JEXEC') or die;
// phpcs:enable PSR1.Files.SideEffects

/**
 * The products controller
 *
 * @since  4.0.0
 */
class ProductsController extends ApiController
{
  /**
   * The content type of the item.
   *
   * @var    string
   * @since  4.1.0
   */
  protected $contentType = 'products';

  /**
   * The default view for the display method.
   *
   * @var    string
   * @since  3.0
   */
  protected $default_view = 'products';

  public function edit()
  {
    Form::addFormPath(JPATH_ADMINISTRATOR . '/components/com_phocacart/models/forms');
    Form::addFieldPath(JPATH_ADMINISTRATOR . '/components/com_phocacart/models/fields');
    return parent::edit(); // TODO: Change the autogenerated stub
  }

  public function getModel($name = '', $prefix = '', $config = [])
  {
    if ($name === 'products')
      $name = 'items';
    if ($name === 'product')
      $name = 'item';
    BaseDatabaseModel::addIncludePath(JPATH_ADMINISTRATOR . '/components/com_phocacart/models');
    return BaseDatabaseModel::getInstance('PhocaCart' . $name, 'PhocaCartCpModel', $config);
  }
}
